"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Stage A：所有可调参数集中在 config.py，通过同名环境变量覆盖
# 默认行为与改前一致（DB_REPLICA_ENABLED/PGBOUNCER_ENABLED 默认 False）
from .config import (
    DB_DEFAULT_NAME, DB_DEFAULT_USER, DB_DEFAULT_PASSWORD,
    DB_DEFAULT_HOST, DB_DEFAULT_PORT,
    DB_CONNECT_TIMEOUT, DB_KEEPALIVES_IDLE, DB_KEEPALIVES_INTERVAL,
    DB_KEEPALIVES_COUNT, DB_CONN_MAX_AGE,
    DB_REPLICA_ENABLED, DB_REPLICA_NAME, DB_REPLICA_USER,
    DB_REPLICA_PASSWORD, DB_REPLICA_HOST, DB_REPLICA_PORT,
    PGBOUNCER_ENABLED, PGBOUNCER_HOST, PGBOUNCER_PORT,
    REDIS_HOST, REDIS_PORT, REDIS_PASSWORD,
    REDIS_DB_CACHE, REDIS_DB_CHANNEL, REDIS_DB_CELERY, REDIS_PROTOCOL,
    ES_ENABLED, ES_HOSTS, ES_USER, ES_PASSWORD,
    ES_INDEX_PREFIX, ES_FLUSH_INTERVAL, ES_BATCH_SIZE,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOGGER_ROOT = os.path.join(BASE_DIR, 'logger')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

APP_NAME = "my_app"
PROJECT_NAME = "my_project"
STATIC_NAME = "my_static"
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&8ue%+g+nyf8oy6ctogjia!q$o_qv@^sr44&px*63_k!=^$192'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'django.contrib.gis',
    # 项目工程
    APP_NAME,
    # rest framework框架
    'rest_framework',
    'rest_framework_gis',
    # 过滤器
    'django_filters',
    # 身份认证
    'rest_framework.authtoken',
    # API 文档（drf-spectacular 替代已停止维护的 rest_framework_swagger）
    'drf_spectacular',
    # 跨域
    'corsheaders',
    'channels'
    # 'sslserver',
    # 'werkzeug_debugger_runserver',
    # 'django_extensions'

]
# AUTH_USER_MODEL = "{}.SysUser".format(APP_NAME)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 阶段 7：RequestContextMiddleware 必须排在 EncryptionMiddleware 之前，
    # 这样 EncryptionMiddleware 里的 logger.info() 才能在 ES 文档里拿到 request_id
    '{}.middleware.RequestContextMiddleware'.format(APP_NAME),
    '{}.middleware.DisableCSRF'.format(APP_NAME),
    '{}.middleware.CORSMiddleware'.format(APP_NAME),
    '{}.middleware.EncryptionMiddleware'.format(APP_NAME)

]

# # SECURITY安全设置 - 支持http时建议开启
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# # SECURE_SSL_REDIRECT = True # 将所有非SSL请求永久重定向到SSL
# SESSION_COOKIE_SECURE = True  # 仅通过https传输cookie
# CSRF_COOKIE_SECURE = True  # 仅通过https传输cookie
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # 严格要求使用https协议传输
# SECURE_HSTS_PRELOAD = True  # HSTS为
# SECURE_HSTS_SECONDS = 60
# SECURE_CONTENT_TYPE_NOSNIFF = True  # 防止浏览器猜测资产的内容类型

# 跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = (
#     '*'
# )

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
    'Localization',  # 支持跨域的 header 里赋 Localization（多语言）
)

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 身份认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        '{}.token.ExpiringTokenAuthentication'.format(PROJECT_NAME)  # 自定义token认证，增加了token失效时间
        # 'rest_framework.authentication.TokenAuthentication',  # token认证
    ),
    # 权限认证
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # IsAuthenticated 仅通过认证的用户
        'rest_framework.permissions.AllowAny',  # AllowAny 允许所有用户
        'rest_framework.permissions.IsAdminUser',  # IsAdminUser 仅管理员用户
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # IsAuthenticatedOrReadOnly 认证的用户可以完全操作，否则只能get读取
    ),
    # 过滤器
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend', 'rest_framework.filters.OrderingFilter'),
    # 分页
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 分页
    'DEFAULT_PAGINATION_CLASS': 'my_project.customPageNumberPagination.CustomPageNumberPagination',
    'PAGE_SIZE': 10,  # 每页数目
    #  API 文档（drf-spectacular）
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

ROOT_URLCONF = '{}.urls'.format(PROJECT_NAME)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {  # Adding this section should work around the issue.
                'staticfiles': 'django.templatetags.static',
            },
        },
    },
]

WSGI_APPLICATION = '{}.wsgi.application'.format(PROJECT_NAME)
ASGI_APPLICATION = '{}.asgi.application'.format(PROJECT_NAME)
# 指定日志的目录所在，如果不存在则创建
LOG_ROOT = os.path.join(BASE_DIR, 'log')
if not os.path.exists(LOG_ROOT):
    os.mkdir(LOG_ROOT)

# 日志配置（基本跟原生的TimedRotatingFileHandler一样）
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] [%(filename)s:%(lineno)d] [%(module)s:%(funcName)s] '
                      '[%(levelname)s]- %(message)s'},
        'simple': {  # 简单格式
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'servers': {
            'class': '{}.log.InterceptTimedRotatingFileHandler'.format(PROJECT_NAME),  # 这个路径看你本地放在哪里(下面的log文件)
            # 路径可以设置在外部，并同步到宿主机
            'filename': os.path.join(LOG_ROOT, 'myapp.log'),
            # 每天自动归档写新的日志文件
            'when': "D",
            'interval': 1,
            'backupCount': 1,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'db': {
            'class': '{}.log.InterceptTimedRotatingFileHandler'.format(PROJECT_NAME),  # 这个路径看你本地放在哪里
            'filename': os.path.join(LOG_ROOT, 'myapp_db.log'),
            # 每天自动归档写新的日志文件
            'when': "D",
            'interval': 1,
            'backupCount': 1,
            'formatter': 'standard',
            'encoding': 'utf-8',
            'logging_levels': ['info']  # 😒注意这里，这是自定义类多了一个参数，因为我只想让db日志有debug文件，所以我只看sql，这个可以自己设置
        },
        # 阶段 7：ES 异步 handler —— 把所有详细日志同步落到 ES，方便 Kibana 可视化
        # 与本地文件日志并行（不动 myapp.log / myapp_db.log 的现有行为）
        # Stage A：ES 配置改读 config.py（环境变量可覆盖）
        'es': {
            'class': '{}.log.ElasticsearchHandler'.format(PROJECT_NAME),
            'level': 'INFO',
            'enabled': ES_ENABLED,
            'es_hosts': list(ES_HOSTS),
            'es_user': ES_USER,
            'es_password': ES_PASSWORD,
            'index_prefix': ES_INDEX_PREFIX,
            'flush_interval': ES_FLUSH_INTERVAL,
            'batch_size': ES_BATCH_SIZE,
            'request_timeout': 5,
        },
    },
    'loggers': {
        # Django全局绑定
        'django': {
            'handlers': ['servers', 'es'],
            'propagate': True,
            'level': "INFO"
        },
        'celery': {
            'handlers': ['servers', 'es'],
            'propagate': False,
            'level': "INFO"
        },
        'django.db.backends': {
            'handlers': ['db', 'es'],
            'propagate': False,
            'level': "DEBUG"
        },
        'django.request': {
            'handlers': ['servers', 'es'],
            'propagate': False,
            'level': "DEBUG"
        },
    }
}

# Redis 地址（缓存 / channels 层 / celery broker 统一指向 192.168.3.80）
# Stage A：值由 config.py 提供（环境变量可覆盖）
# 注意：下方 CHANNEL_LAYERS / CACHES / CELERY_* 都通过这里读 REDIS_HOST/PORT/DB_*。
REDIS_HOST_LOCAL = REDIS_HOST
REDIS_PORT_LOCAL = REDIS_PORT
REDIS_PASSWORD_LOCAL = REDIS_PASSWORD
REDIS_DB_CACHE_LOCAL = REDIS_DB_CACHE
REDIS_DB_CHANNEL_LOCAL = REDIS_DB_CHANNEL
REDIS_DB_CELERY_LOCAL = REDIS_DB_CELERY
REDIS_PROTOCOL_LOCAL = REDIS_PROTOCOL

# 该服务器的 Redis 是 5.0.x，而 redis-py 5.x 起默认走 RESP3 握手（HELLO 3），
# Redis 6.0 才支持 HELLO，直连会报 "unknown command `HELLO`"。
# 因此所有 Redis 连接显式声明 protocol=2（RESP2）。
# 若将来把 Redis 升级到 6.0+，可以把这几处 protocol 去掉。

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{"host": REDIS_HOST_LOCAL, "port": REDIS_PORT_LOCAL, "protocol": REDIS_PROTOCOL_LOCAL}],
            "prefix": "vgis_channel",  # 前缀隔离，避免与其他服务串频道
            "capacity": 1500,
            "expiry": 10,
        },
    },
}

# Redis缓存库配置
# Stage A：值由 config.py 提供
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://{}:{}/{}".format(REDIS_HOST_LOCAL, REDIS_PORT_LOCAL, REDIS_DB_CACHE_LOCAL),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "CONNECTION_POOL_KWARGS": {"max_connections": 512, "protocol": REDIS_PROTOCOL_LOCAL},
            # 注意：开启后 Redis 不可用时 cache 操作会静默返回 None 而不报错，
            # 排查缓存问题时应临时关掉。
            "IGNORE_EXCEPTIONS": True,
            "SOCKET_CONNECT_TIMEOUT": 5,  # in seconds
            "SOCKET_TIMEOUT": 5,  # in seconds
        }
    }
}

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# Stage B：连接硬化（libpq keepalive + statement_timeout + idle_in_transaction_session_timeout），
#         并按 config.py 中的开关决定是否加 replica / 走 pgbouncer。

def _build_db_options():
    """libpq 选项集中在此，便于按 env 统一调整"""
    return {
        "connect_timeout": DB_CONNECT_TIMEOUT,
        "keepalives": 1,
        "keepalives_idle": DB_KEEPALIVES_IDLE,
        "keepalives_interval": DB_KEEPALIVES_INTERVAL,
        "keepalives_count": DB_KEEPALIVES_COUNT,
        # PG 会话级超时：单语句 30s、空闲事务 60s 强制断开
        "options": "-c statement_timeout=30s -c idle_in_transaction_session_timeout=60s",
    }


def _build_db_block(user, password, host, port, dbname):
    return {
        # PostGIS 引擎（Django 6 下需要 GDAL/GEOS，见文件末尾的 GDAL_LIBRARY_PATH 配置）
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": dbname,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": str(port),
        "OPTIONS": _build_db_options(),
        # CONN_MAX_AGE=60：连接保留 60 秒，避免每请求重连（PG 端 max=100，需配合）
        # CONN_HEALTH_CHECKS=True：在拿连接前做一次健康检查，剔除已被服务端关闭的连接
        "CONN_MAX_AGE": DB_CONN_MAX_AGE,
        "CONN_HEALTH_CHECKS": True,
    }


DATABASES = {
    "default": _build_db_block(
        DB_DEFAULT_USER, DB_DEFAULT_PASSWORD,
        DB_DEFAULT_HOST, DB_DEFAULT_PORT, DB_DEFAULT_NAME,
    ),
}
if DB_REPLICA_ENABLED:
    DATABASES["replica"] = _build_db_block(
        DB_REPLICA_USER, DB_REPLICA_PASSWORD,
        DB_REPLICA_HOST, DB_REPLICA_PORT, DB_REPLICA_NAME,
    )
if PGBOUNCER_ENABLED:
    # 走 pgbouncer 时所有 alias 统一指向 pgbouncer 监听地址
    # 注意 pgbouncer 模式下 CONN_MAX_AGE 必须为 0，但本项目默认直连，
    # 所以默认行为下不会进入此分支。
    for alias in DATABASES:
        DATABASES[alias]["HOST"] = PGBOUNCER_HOST
        DATABASES[alias]["PORT"] = str(PGBOUNCER_PORT)

# 读副本路由：仅当 DB_REPLICA_ENABLED 时把读流量切到 replica
DATABASE_ROUTERS = ["my_project.db_router.PrimaryReplicaRouter"]

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# 设置为中文
LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# 注意：USE_L10N 在 Django 4.0 弃用、5.0 移除，这里不能再声明
# 不用世界时
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


STATICFILES_DIRS = [os.path.join(BASE_DIR, '{}/{}'.format(APP_NAME, STATIC_NAME))]

# 根据项目名称修改url
STATIC_URL = '/{}/'.format(STATIC_NAME)

# STATIC_ROOT = os.path.join(BASE_DIR, '{}'.format(APP_NAME), '{}'.format(STATIC_NAME))

# 上传文件目录
UPLOAD_ROOT = os.path.join(BASE_DIR, '{}'.format(APP_NAME), '{}'.format(STATIC_NAME), 'upload')

# 是否使用模拟数据
IS_USE_MOCK_DATA = False

# token失效时间，单位秒，开发可自行配置
AUTH_TOKEN_AGE = 60 * 60 * 3

# 项目部署的IP、端口号、网络协议
PROJECT_WEB_PROTOCOL = 'http'
PROJECT_SERVICE_IP = '192.168.3.152'
# 用nginx代理出来实现后端跨域的端口
PROJECT_SERVICE_PORT = '10841'

# 广西服务器
# PROJECT_SERVICE_IP = '117.141.148.176'
# PROJECT_SERVICE_PORT = '14001'

# 是否开启验证码
IS_USE_VERIFICATION_CODE = False

# 是否对请求响应做加解密
IS_ENCRYPTION = False

# 登录失败尝试次数
LOGIN_ERROR_ATTEMPTS = 4

# 账号锁定后的解锁时间，单位秒
LOGIN_LOCKED_TIME = 10 * 60

# Token的key
TOKEN_KEY = 'Authorization'

# 本地化的key,不能太长（请求头里带 Localization: CH / EN）
LOCAL_KEY = 'Localization'

# 分页每页最大条数
PAGE_MAX_SIZE = 200

# TOKEN是否用缓存
TOKEN_USE_CACHE = False

# 加密相关信息
ENCRPTION = {
    "key1": "uNl-LfGm6NKDQ1Uz9azZIEEzYnaLz68gz0UzaQvYFIY=",
    "key2": "Z0FBQUFBQmsyZWJGZl81NGRMVG9zTVdtQmhTalhfQkhvRVlaVElCMm1ubnZHTXFOb1otNG40ODFlX1JDNk5udmZQaWxrTTI4ODNsVjZyYVZNZDZUZ3NnbS0wMGpEVE1JZFVWS3pkU0pkWVpWcG1ZaTRoeHJDQTd1UXo1Mk5tZ19sdlZUUC1HZ0xiUkNKYWFhcVNuaTFMcTZSam96b3liZmNfMUtKYUxUdldkM3lyVngtYUZleE0zVEZ1cHlkTGdFRVlOQkhlR2dkT191VjJOWXFWSF9YamNuZkE1cURJTlpmWWpUZS1ON2lDZmlNX1MzSzk4eVFEQ2E1MHFTMUpCYjJVRVhrX2pDaEIwcnhVb3lvQ3hqRWF5aTJNVFYwamNtamxyYzFlMXFjaFpDVDBCZkhQdTFma1kwVV93dVNFamlpNUY1ejZIWG1VNEhfMGh0N1hrYXNfcnBobzZ5X1RtVXRiOUtWelZPTFpsNmVxc2xqUHdGYkswPQ==",
    "key3": "Z0FBQUFBQmsyZWJGOWxzeWtGZnVwa0tNdFBQSG1GSkxfRXZPS2lScmtMSHBZM0w4M3FJdXY1N0JHTlRwYjFILXY0akl0NjVvSFA0bkdWdENtTUx6czFab3AwQkpoQ1VNeXJ2QUFTMU9NZ200ZzlVMWZWdTU3eWt0WjhnaElZVzN3WUxZTzFZMkF6czhFN19JWk9zZmRsSDRBdzZuUUVQQW5VbFJpZ1oxVVdlVkVNWEJkSVdGX0VVNEZrRDUtQVFrQm9zalphRkxzLVBGanlnTEhUb0VPaE5YYnBaeDJaUm1laHRUOUxNamIycFMyMDlnYkJ0NTFpZVZxaElkZXlUcEQ5eUJBUTZBVkNkVHI5UktVeFJDMjlXNlhaVWNEZnNlZ09ZWE42Nk52eG9lWnNWOURVRVV4SVFGaGNVM2tuOVBiTHFyQzJOTzNFMUpMendYdWF4ZzBPWnBfc1RXWGxNMnJiNWxsRzQ0Uk12RF85NTR0U2I5SzdQSXc2c1c3N0w2T1cteTNPcWZhdHM0SHlYdXllbkc5ZG04V25TbHdrMC0xRHBXVktQTW1TT3pFMmZsZkNReDczanphYXlxNnpmaE5Db1k0ejBpNVo5N1owM0M4UVNJUWZNUmFSZVctQklaeG5LZE90amNTNHlCU1lzY1B6ZGlfRVczRk05T09udG14OWlSaXZWVnh0dmtwLXJvZUU1MFl4WjBRX0lIaUJhZF9RNTB2a2VYeUtaMmhmY2xTRWtJNFVBX0dHMnNKOGhYRF82bVJDa2Jfck5CeVhIU3BOQW82QmJwZjdXVUhZSEMxSGEwaUk3a0pwS3BoSDRoMDhkblNYVVlyQWV3QWVFSFdIZ1IydE5yeWRwd1ZtR1h6MXJsS28wWWZ6VWtUZzlWZG1nQjE3M1JOQUVvcjg4NThzczZmazg0Tmp6SjNzZXNCanpIek5YRnp0YXZhbFdhWDNYMV9NYXJFMExtZXdYLXhsZ3k2T3g5YlduV1hJRFEzbFVsTDhRYWZ0WFZNTEo3dlFyTHFKREV0ZWxJYnJKN3RRZmt3cE9Bc3F5TlZ3WVg4YTY4VW5MbnZuVkhudllTQ052S3ZwSWx5c2tuX1FuZ1F6ejAyTVZrUG5meTU2c2NSbWs2ZDlDUVA5QXdMLU9Sc3FqVVF6RXB0UG9YNkZSTnRreXZIR05qRW9JQkp4MmU2amw5YlhqZzl2RlFYS0lIck9HU3hHS185em1qLTY1UnV3eDl5SGFyT1lpV1REY3NsMzhEOEh1NFlHMHkwNlpWdWpuTGFVemtTSGFLZmZZWE02ZE1HcGxjRC1nR2NPb0Q3S0FjdXlpNEJjRWlER2h0X1VQR1VuZ0YwNEpzWVZvbmxDaXBSQ0dwSHBYTDBwZ1AycjFSd1pibndFRW41UjNtQzVIczVzYzgyQjdWZ2VlMm5kbnNVN1FqTlVHWHdoRGR2QUVXWGZnZFRRZVlNRk1xZHNGcVVCcEw3RmRsaVUtM29aZHZycV93cXByR291T0dxWnhBVF9VS0FaNjJJb29XOEhpbzBKa2JXbGJBY1Q3VFZGd1BqSGp3LVpaR0p5NGlwZUZfREV0dUNZSG90bnRQU3hPOUxweURyTlB4X3l6VHZRdDFGejREbVQ1QQ==",
    "key4": "b3sVBbMdxJ2pgK/XYPpKVEYdVNk8bUBt9bcpCMegEec3m/nfbvdvVgPlEm1Yd6aavB8jdUR1HF1vf13l/ADVddg6Cl1Yl+vXkDaKeKHa7bHoJpLAWt7i0mIVHSMhPJdQb2qRTbaPCu8MRZNsJWivgnnTSGEHy+vvGhvxCeWcmB0="
}

# 许可文件的路径（登录接口会校验，缺失或过期都会拒绝登录）
WINDOWS_LICENSE_PATH = "C:/license/django_study_license.lic"
LINUX_LICENSE_PATH = "/home/root/license/django_study_license.lic"

# 多线程数
MAX_THREAD_COUNT = 16

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# 调试时打开，部署时关闭
# 打开后可以通过url访问static内的静态资源
# 注意：DEBUG 已在文件开头定义，这里不要再重复定义

# 配置celery异步任务使用的redis cache（统一指向 192.168.3.80，独立 DB 避免与缓存/通道层冲突）
# Stage A：值由 config.py 提供（环境变量可覆盖）
CELERY_BROKER_URL = 'redis://{}:{}/{}'.format(REDIS_HOST_LOCAL, REDIS_PORT_LOCAL, REDIS_DB_CELERY_LOCAL)
CELERY_RESULT_BACKEND = 'redis://{}:{}/{}'.format(REDIS_HOST_LOCAL, REDIS_PORT_LOCAL, REDIS_DB_CELERY_LOCAL)
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_TASK_TRACK_STARTED = True
# 任务结果保留 1 天，避免 Redis 无限增长
CELERY_RESULT_EXPIRES = 60 * 60 * 24
# worker 预取数：长任务场景调小可让任务分配更均衡
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# broker 连接重试
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# ===========================================================================
# GIS 原生库路径（GDAL / GEOS / PROJ）
#
# 为什么必须显式配置（Windows）：
#   1) django.contrib.gis 需要 GDAL 动态库，而 Django 只按
#      gdal311 / gdal310 / ... / gdal300 这类"带版本号"的文件名去找；
#      conda-forge 构建的 GDAL 文件名是裸的 gdal.dll，自动发现必然失败，
#      报 "Could not find the GDAL library (tried gdal311, gdal310, ...)"。
#   2) venv 里自带的 osgeo Python 绑定（_gdal.pyd）依赖**同目录**的 gdal.dll。
#      若 Django 指向另一份 GDAL（例如旧的 C:\Program Files\GDAL，3.0.4），
#      同一进程会加载两个版本的 GDAL，且 osgeo 会直接 ImportError。
#      所以这里优先选与 venv 配套的那一份。
#
# 可用环境变量 GDAL_BIN_DIR 覆盖（优先级最高），便于换机器/换版本。
# 部署到 Linux 时本节自动跳过（服务器上一般已在 ld 路径里）。
# ===========================================================================
import os as _os

if _os.name == 'nt':
    # 与 venv_6.06 配套的那份 GDAL（venv 里的 osgeo 绑定依赖它同目录的 gdal.dll）
    _GDAL_PREFERRED = r'E:\claudecode\_tools\gdal-3.13.3\Library\bin'

    # 候选目录按优先级排列
    _GDAL_CANDIDATES = [
        _os.environ.get('GDAL_BIN_DIR'),    # 显式指定，最高优先级
        _GDAL_PREFERRED,                    # 与 venv_6.06 配套的 GDAL 3.13.3
        r'C:\Program Files\GDAL\bin',       # 旧的独立安装（GDAL 3.0.x），仅兜底
        r'C:\OSGeo4W64\bin',
        r'C:\OSGeo4W\bin',
    ]
    # 不同发行版对 GDAL 主库的命名不同，按常见顺序找
    _GDAL_DLL_NAMES = ['gdal.dll', 'gdal313.dll', 'gdal311.dll',
                       'gdal310.dll', 'gdal309.dll', 'gdal300.dll']

    for _base in _GDAL_CANDIDATES:
        if not _base or not _os.path.isdir(_base):
            continue
        _gdal_dll = next((_os.path.join(_base, n) for n in _GDAL_DLL_NAMES
                          if _os.path.exists(_os.path.join(_base, n))), None)
        if _gdal_dll is None:
            continue

        # 把该目录加进 DLL 搜索路径，让 _gdal.pyd / GEOS / PROJ 等能定位到同目录依赖
        try:
            _os.add_dll_directory(_base)
        except (AttributeError, OSError):
            pass
        # 同时置于 PATH 最前：子进程、以及靠 PATH 定位原生库的第三方包
        # （pyproj / fiona / rasterio / geopandas）才能用到同一份 GDAL
        if _base not in _os.environ.get('PATH', '').split(_os.pathsep):
            _os.environ['PATH'] = _base + _os.pathsep + _os.environ.get('PATH', '')

        GDAL_LIBRARY_PATH = _gdal_dll
        _geos = _os.path.join(_base, 'geos_c.dll')
        if _os.path.exists(_geos):
            GEOS_LIBRARY_PATH = _geos

        # 用到的不是与 venv 配套的那份 GDAL 时给出明确警告。
        # 否则一旦配套目录被删/改名，会静默回落到旧的 3.0.x：Django 侧照样能启动，
        # 但 venv 的 osgeo 会报 "DLL load failed while importing _gdal"，
        # 而报错完全指不到"GDAL 选错了"，排查很绕。
        if _base != _GDAL_PREFERRED:
            import warnings as _warnings

            _warnings.warn(
                "[VGIS] 当前选用的 GDAL 不是与 venv 配套的那份，osgeo 绑定可能不可用。\n"
                "       实际选用: {}\n"
                "       配套路径: {}{}\n"
                "       影响: venv 里 osgeo 的 _gdal.pyd 依赖【同目录】的 gdal.dll，"
                "版本不配套时 import osgeo 会失败，且进程内可能同时加载两个版本的 GDAL。\n"
                "       处理: 确认上面的配套路径存在；或把它设到环境变量 GDAL_BIN_DIR 显式指定。".format(
                    _base,
                    _GDAL_PREFERRED,
                    _os.environ.get('GDAL_BIN_DIR') and "（GDAL_BIN_DIR 已设为 {}）".format(
                        _os.environ['GDAL_BIN_DIR']) or "",
                ),
                RuntimeWarning,
                stacklevel=1,
            )

        # PROJ/GDAL 数据目录：conda 版在 <prefix>/share/xxx，独立安装版在 bin/proj、bin/gdata
        #
        # 注意：这里必须**直接覆盖**而不是 setdefault。
        # 本机系统级环境里装过 GeoServer/GISInternals，已存在
        #   PROJ_LIB=C:\Program Files\gdal\bin\proj6\share      （2019 年的 proj.db）
        #   GDAL_DATA=C:\Program Files\gdal\bin\gdal-data
        #   GDAL_DRIVER_PATH=C:\Program Files\gdal\bin\gdal\plugins
        # 这些属于旧的 GDAL 3.0.4。若保留，新版 GDAL 会读到旧 proj.db 并报
        # "proj.db lacks DATABASE.LAYOUT.VERSION.MAJOR ... It comes from another PROJ installation"，
        # 或加载到为旧版编译的驱动插件。既然已经选定了某份 GDAL，就用它配套的数据目录。
        _prefix = _os.path.dirname(_base)
        for _p in (_os.path.join(_prefix, 'share', 'proj'),      # conda: Library/share/proj
                   _os.path.join(_base, 'proj')):                 # GISInternals: bin/proj
            if _os.path.isdir(_p):
                _os.environ['PROJ_LIB'] = _p
                break
        for _g in (_os.path.join(_prefix, 'share', 'gdal'),      # conda: Library/share/gdal
                   _os.path.join(_base, 'gdata')):                # GISInternals: bin/gdata
            if _os.path.isdir(_g):
                _os.environ['GDAL_DATA'] = _g
                break

        # 驱动插件目录：只有选定的 GDAL 自己有才设，否则清掉外部残留值，
        # 避免加载到为其它 GDAL 版本编译的插件
        _plugins = next((p for p in (_os.path.join(_prefix, 'lib', 'gdalplugins'),  # conda
                                     _os.path.join(_base, 'gdal', 'plugins'))       # GISInternals
                         if _os.path.isdir(p)), None)
        if _plugins:
            _os.environ['GDAL_DRIVER_PATH'] = _plugins
        else:
            _os.environ.pop('GDAL_DRIVER_PATH', None)
        break

# ===========================================================================
# API 文档（drf-spectacular）
# 访问 /docs/ 查看 Swagger UI，/docs/schema/ 取 OpenAPI schema
# ===========================================================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'VGIS Django 框架 API',
    'DESCRIPTION': '系统管理 / 认证 / 上传 / 行政区划等通用接口',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # DRF 的 Token 认证在文档里以 Authorization 头体现
    'SECURITY': [{'Token': []}],
    'COMPONENT_SPLIT_REQUEST': True,
}

# ===========================================================================
# gis_service 模块配置（GIS_SSH / MINIO / TITILER / PGSTAC / NGINX）
#
# Stage A 的所有可调参数都在 config.py 里通过同名环境变量覆盖，
# 这里只做 from-import，方便其它地方用 settings.GIS_* 取值。
#
# 设计原则：
#   1) Vector 数据走现有 MYDB（DATABASES['default']），不另开库
#   2) 重型发布（PMTiles / COG / STAC ingest）走 Celery 异步
#   3) MVT 瓦片由 Django 直查 MYDB 渲染（不依赖 TiTiler）；COG 瓦片反代 TiTiler
#   4) SSH/MinIO 只在 Celery 异步任务里用，HTTP 路径不直接连
# ===========================================================================
from .config import (  # noqa: E402
    GIS_SSH_HOST, GIS_SSH_PORT, GIS_SSH_USER, GIS_SSH_PASSWORD,
    GIS_MINIO_ENDPOINT, GIS_MINIO_USER, GIS_MINIO_PASSWORD, GIS_MINIO_BUCKET,
    GIS_TITILER_URL, GIS_PGSTAC_DSN,
    GIS_NGINX_HOST, GIS_NGINX_PORT, GIS_WORK_DIR,
)
