-- ============================================================================
-- MYDB 升级脚本：把 MYDB 补齐到 Django 框架 my_project 所需的表结构
--
-- 背景：MYDB（192.168.3.80）原本只有系统管理相关的 26 张表，
--       缺少框架运行必需的部分表与列。本脚本与 PNT 库对比后生成。
-- 原则：只做加法（CREATE TABLE / ADD COLUMN IF NOT EXISTS），
--       不改写、不删除任何现有列与数据，可安全重复执行。
-- 执行：psql -h 192.168.3.80 -U postgres -d MYDB -f MYDB_upgrade.sql
-- 生成日期：2026-09-12
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 一、新建缺失的表
-- ---------------------------------------------------------------------------

-- 1. sys_param 系统参数表
--    框架的所有运行开关都从这里读：AUTH_TOKEN_AGE / IS_ENCRYPTION /
--    IS_USE_VERIFICATION_CODE / LOGIN_ERROR_ATTEMPTS / LOGIN_LOCKED_TIME /
--    TOKEN_KEY / TOKEN_USE_CACHE。缺这张表则每个请求都会报错。
--    结构取自 PNT.sys_param，额外补上主键与自增（PNT 侧无 PK）。
CREATE TABLE IF NOT EXISTS sys_param (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    param_en_key   varchar(200),
    param_cn_key   varchar(200),
    param_value    varchar(255),
    create_time    timestamp with time zone,
    create_user_id bigint,
    update_time    timestamp with time zone,
    update_user_id bigint
);
COMMENT ON TABLE sys_param IS '系统参数表';

-- 2. tt_userpass_question 密保问题字典（忘记密码功能用）
--    结构取自 PNT.tt_userpass_question，补上自增以便新增题目。
CREATE TABLE IF NOT EXISTS tt_userpass_question (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question varchar(1000)
);
COMMENT ON TABLE tt_userpass_question IS '用户密保问题表';

-- 3. sys_dict 数据字典表（SysDictViewSet 用；PNT 与 MYDB 均无，按代码模型新建）
CREATE TABLE IF NOT EXISTS sys_dict (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_catelog_id bigint,
    type_value     varchar(200),
    memo_value     varchar(200),
    param_value    varchar(255),
    create_time    timestamp without time zone,
    create_user_id bigint,
    update_time    timestamp without time zone,
    update_user_id bigint
);
COMMENT ON TABLE sys_dict IS '系统字典表';

-- 4. sys_message 系统消息表（SysMessageViewSet 用；两边均无，按代码模型新建）
--    create_time：sysManager.sql_search_message 的时间条件依赖该列（原 SQL 还错写成
--    未定义别名 tableb.create_time），缺列会让「消息列表按时间检索」直接报错，故一并建上。
CREATE TABLE IF NOT EXISTS sys_message (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint,
    message     varchar(2550),
    create_time timestamp without time zone
);
COMMENT ON TABLE sys_message IS '系统消息表';

-- 5. tt_retrivepass_token 密码找回一次性令牌表（两边均无，按代码模型新建）
--    注意：key 是 PG 非保留字，但 Django 会加引号，这里保持一致加引号。
CREATE TABLE IF NOT EXISTS tt_retrivepass_token (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key"       varchar(1000),
    user_id     bigint,
    create_time timestamp without time zone
);
COMMENT ON TABLE tt_retrivepass_token IS '密码找回令牌表';

-- ---------------------------------------------------------------------------
-- 二、给现有表补齐代码声明的列
-- ---------------------------------------------------------------------------

-- auth_user：
--   login_error_attempts / login_locked_until —— AuthUser 模型声明了这两列，
--     ORM 每次查询都会 SELECT 它们，缺列会导致登录直接报错（登录锁定功能失效）。
--   userpass_question / userpass_answer —— 忘记密码走裸 SQL 读取，缺列则找回密码报错。
ALTER TABLE auth_user
    ADD COLUMN IF NOT EXISTS login_error_attempts smallint DEFAULT 0,
    ADD COLUMN IF NOT EXISTS login_locked_until  timestamp without time zone,
    ADD COLUMN IF NOT EXISTS userpass_question   varchar(2550),
    ADD COLUMN IF NOT EXISTS userpass_answer     varchar(2550);

-- sys_log：error_info —— SysLog 模型声明为 TextField，
--   写操作日志（LoggerHelper.insert_log_info）时会用到，缺列则记日志报错。
ALTER TABLE sys_log
    ADD COLUMN IF NOT EXISTS error_info text;

-- tt_upload_file_data：补齐代码声明但 MYDB 缺失的三列。
ALTER TABLE tt_upload_file_data
    ADD COLUMN IF NOT EXISTS upload_user_id bigint,
    ADD COLUMN IF NOT EXISTS file_size      numeric(24, 0),
    ADD COLUMN IF NOT EXISTS file_id        varchar(255);

-- tt_upload_file_data.id：MYDB 原为 uuid 且无默认值，而代码模型声明 BigAutoField，
-- 直接 create() 会因主键无值而失败（文件上传功能不可用）。
-- 这里把 id 重建为 bigint 自增。脚本自带守卫：仅当 id 仍是 uuid 时才执行，
-- 且表中有数据时会主动报错中止，避免丢数据。
DO $$
DECLARE
    id_type text;
    row_cnt bigint;
    cname   text;
BEGIN
    SELECT data_type INTO id_type FROM information_schema.columns
    WHERE table_schema='public' AND table_name='tt_upload_file_data' AND column_name='id';

    IF id_type = 'uuid' THEN
        SELECT count(*) INTO row_cnt FROM tt_upload_file_data;
        IF row_cnt > 0 THEN
            RAISE EXCEPTION 'tt_upload_file_data 非空(% 行)，id 类型变更需人工处理，脚本中止', row_cnt;
        END IF;

        FOR cname IN SELECT conname FROM pg_constraint
                     WHERE conrelid='public.tt_upload_file_data'::regclass AND contype='p'
        LOOP
            EXECUTE format('ALTER TABLE tt_upload_file_data DROP CONSTRAINT %I', cname);
        END LOOP;

        ALTER TABLE tt_upload_file_data DROP COLUMN id;
        ALTER TABLE tt_upload_file_data
            ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
        RAISE NOTICE 'tt_upload_file_data.id 已由 uuid 重建为 bigint 自增';
    ELSE
        RAISE NOTICE 'tt_upload_file_data.id 已是 %，跳过', id_type;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 三、预置数据
-- ---------------------------------------------------------------------------

-- sys_param 的 7 个框架开关。
-- 注意：PNT 库里 IS_ENCRYPTION 与 IS_USE_VERIFICATION_CODE 都是"是"（生产配置），
--       这里按框架 settings.py 的默认值取"否"，便于本地联调；
--       要开启改这两行即可：UPDATE sys_param SET param_value='是' WHERE param_en_key='IS_ENCRYPTION';
INSERT INTO sys_param (param_en_key, param_cn_key, param_value) VALUES
    ('IS_ENCRYPTION',            '是否请求响应加解密', '否'),
    ('LOGIN_ERROR_ATTEMPTS',     '登录失败尝试次数',   '4'),
    ('LOGIN_LOCKED_TIME',        '账号锁定后的解锁时间（秒）', '600'),
    ('TOKEN_KEY',                'Token的key名称',     'Authorization'),
    ('AUTH_TOKEN_AGE',           'Token失效时间(秒)',  '10800'),
    ('IS_USE_VERIFICATION_CODE', '是否开启验证码',     '否'),
    ('TOKEN_USE_CACHE',          'TOKEN是否用缓存',    '否')
ON CONFLICT DO NOTHING;

-- 密保问题字典：取自 PNT.tt_userpass_question（4 条）
INSERT INTO tt_userpass_question (id, question) VALUES
    (1820243275055105, '你母亲的名字是什么？'),
    (1820243275055106, '你小学的班主任是什么？'),
    (1820243275055107, '你最喜欢的电影是什么？'),
    (1820243275055108, '你童年最珍贵的偶像是谁？')
ON CONFLICT DO NOTHING;

COMMIT;

-- ============================================================================
-- 执行后自检（应全部返回 t）
-- ============================================================================
-- SELECT to_regclass('public.sys_param'), to_regclass('public.sys_dict'),
--        to_regclass('public.sys_message'), to_regclass('public.tt_userpass_question'),
--        to_regclass('public.tt_retrivepass_token');
-- SELECT count(*) FROM sys_param;                -- 期望 7
-- SELECT count(*) FROM tt_userpass_question;     -- 期望 4
-- SELECT column_name FROM information_schema.columns
--   WHERE table_name='auth_user' AND column_name LIKE '%login%' OR column_name LIKE 'userpass%';
--
-- ============================================================================
-- 已知遗留（不影响框架运行，属历史结构差异，未处理）
-- ============================================================================
-- 1) auth_user.id 是 integer（带 auth_user_id_seq），代码模型声明 BigAutoField。
--    实际可用：Django 读写 integer 主键没问题，用户量也不可能超 int 上限。
-- 2) sys_log.time 是 real，代码模型声明 FloatField（映射 double precision）。
--    实际可用：该列存的是接口耗时（秒），real 的精度足够。
-- 3) WorldBorder 模型（tm_world_border 表）在 MYDB 与 PNT 中都不存在，
--    是 GeoDjango 示例残留，框架未使用。建议直接删除该模型与 my_app/load.py，
--    而不是给它建表。
-- ============================================================================
