-- ============================================================================
-- demo 模块演示表：tt_demo_item
--
-- 用途：作为框架「SQL CRUD + 裸 SQL 分页 + 多表联合查询 + Excel 导入导出」
--       的完整模板载体。字段刻意设计了两个外键指向既有系统表，
--       让「多表联合查询」有真实意义：
--         category_id   → sys_dict_catelog.id
--         department_id → sys_department.department_id
--
-- item_code 上建 UNIQUE 索引 —— 这是 Excel 导入 upsert 的依据
-- （ON CONFLICT (item_code) DO UPDATE），也是参考项目缺失的那一层保障：
-- 保险OCR 项目靠应用层 filter() 先查后写且库上无唯一约束，存在 TOCTOU 竞态。
--
-- 可重复执行：建表/索引都用 IF NOT EXISTS，种子数据用 ON CONFLICT DO NOTHING
-- 执行：psql -h 192.168.3.40 -p 12326 -U postgres -d MYDB -f tt_demo_item.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS tt_demo_item (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code      varchar(64)  NOT NULL,             -- 业务唯一编码（导入 upsert 依据）
    item_name      varchar(255) NOT NULL,
    category_id    bigint,                            -- → sys_dict_catelog.id
    department_id  bigint,                            -- → sys_department.department_id
    amount         numeric(18, 2),
    item_status    smallint DEFAULT 1,                -- 1 启用 / 0 停用
    occur_date     date,
    remark         varchar(500),
    create_user_id bigint,
    create_time    timestamp without time zone,
    modify_user_id bigint,
    modify_time    timestamp without time zone
);
COMMENT ON TABLE tt_demo_item IS 'demo 模块演示表（CRUD/分页/Excel 模板载体）';

-- 导入 upsert 依赖这个唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS uk_tt_demo_item_code ON tt_demo_item (item_code);

-- 联合查询与筛选常用列建索引
CREATE INDEX IF NOT EXISTS idx_tt_demo_item_category   ON tt_demo_item (category_id);
CREATE INDEX IF NOT EXISTS idx_tt_demo_item_department ON tt_demo_item (department_id);
CREATE INDEX IF NOT EXISTS idx_tt_demo_item_occur_date ON tt_demo_item (occur_date);

-- ---------------------------------------------------------------------------
-- 种子数据：35 条（默认每页 10 条 → 刚好 4 页，便于验证分页）
-- ---------------------------------------------------------------------------
INSERT INTO tt_demo_item (item_code, item_name, category_id, department_id, amount,
                          item_status, occur_date, remark, create_user_id, create_time)
SELECT
    'DEMO' || lpad(g::text, 4, '0'),
    '演示数据 ' || g,
    (ARRAY[1, 2, 3])[1 + (g % 3)],
    (SELECT department_id FROM sys_department WHERE del_flag = 0
      ORDER BY department_id OFFSET (g % 5) LIMIT 1),
    round((random() * 10000)::numeric, 2),
    CASE WHEN g % 7 = 0 THEN 0 ELSE 1 END,
    CURRENT_DATE - (g % 30),
    '自动生成的演示数据 #' || g,
    1,
    now()
FROM generate_series(1, 35) AS g
ON CONFLICT (item_code) DO NOTHING;

-- ============================================================================
-- 自检
-- ============================================================================
-- SELECT count(*) FROM tt_demo_item;                                   -- 期望 35
-- SELECT count(*) FROM tt_demo_item WHERE category_id IS NULL;          -- 期望 0
-- SELECT t.item_code, t.item_name, c.dict_catelog_name, d.department_name, t.amount
--   FROM tt_demo_item t
--   LEFT JOIN sys_dict_catelog c ON c.id = t.category_id
--   LEFT JOIN sys_department   d ON d.department_id = t.department_id
--  ORDER BY t.id LIMIT 5;                                               -- 联合查询冒烟
-- ============================================================================
